`timescale 1ns / 1ps

module SequentialWriter(
	/* Standard pins */
	clk,
	rst_n,

	/* Base address of "log" global memory where the timestamps are saved */
	offset,
	/* Command generated by commandUnit */
	command,
	/* Timestamp value to be written */
	value,
	/* Asserted when this module is done/idling */
	idle,

	/* AXI4 Master to global memory */
	axiAWVALID,
	axiAWREADY,
	axiAWADDR,
	axiAWLEN,
	axiAWSIZE,
	axiWVALID,
	axiWREADY,
	axiWDATA,
	axiWSTRB,
	axiWLAST,
	axiBRESP,
	axiBVALID,
	axiBREADY
);

	input clk;
	input rst_n;

	input [63:0] offset;
	input [3:0] command;
	input [63:0] value;
	output idle;

	output axiAWVALID;
	input axiAWREADY;
	output [63:0] axiAWADDR;
	output [7:0] axiAWLEN;
	output [2:0] axiAWSIZE;
	output axiWVALID;
	input axiWREADY;
	output [63:0] axiWDATA;
	output [7:0] axiWSTRB;
	output axiWLAST;
	input [1:0] axiBRESP;
	input axiBVALID;
	output axiBREADY;

	// This module must be always-ready. Therefore a FIFO here will be essential
	// For now, when a transaction is being performed, all following transactions are dropped

	assign idle = 'h00 == state;

	assign axiAWVALID = 'h01 == state;
	assign axiAWADDR = wAddr;
	assign axiAWLEN = 8'h01;
	assign axiAWSIZE = 3'b011;
	assign axiWVALID = 'h02 == state;
	assign axiWDATA = wData;
	assign axiWSTRB = 8'hFF;
	assign axiWLAST = 1'b1;

	assign axiBREADY = 'h03 == state;

	reg [7:0] state;
	reg [63:0] addrCounter;
	reg [63:0] wAddr;
	reg [63:0] wData;

	/* AXI4 Master write logic. This is not pipelined. Transactions are queued in the FIFO. If the FIFO is full, receiving transactions are dropped */
	always @(posedge clk) begin
		if(!rst_n) begin
			state <= 'h00;
			addrCounter <= 'h00;
			wAddr <= 'h00;
			wData <= 'h00;
		end
		else begin
			/* Idle state */
			if('h00 == state) begin
				/* 0x1 command: save timestamp */
				if('h1 == command) begin
					addrCounter <= addrCounter + 'h8;
					wAddr <= offset + addrCounter;
					wData <= value;

					state <= 'h01;
				end
				/* 0x2 command received, reset counter */
				else if('h2 == command) begin
					addrCounter <= 'h00;
				end
			end
			/* Wait for AXI4 Slave to be ready to receive address */
			else if('h01 == state) begin
				if(axiAWREADY) begin
					state <= 'h02;
				end
			end
			/* Wait for AXI4 Slave to be ready to receive data */
			else if('h02 == state) begin
				if(axiWREADY) begin
					state <= 'h03;
				end
			end
			/* Wait for AXI4 Slave to acknowledge that data was received */
			else if('h03 == state) begin
				if(axiBVALID) begin
					state <= 'h00;
				end
			end
			else begin
				state <= 'h00;
			end
		end
	end

endmodule
